version: "3"

services:
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file: .env
    environment:
      DB_URI: postgresql://postgres:postgres@postgres:5432/api
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
